version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/groovy-ssh
    steps:
      - run: mkdir -p $HOME/bin
      - run: echo 'export PATH="$HOME/bin:$PATH"' >> $BASH_ENV
      - run: |
          curl -fL -o /tmp/ghcp.zip https://github.com/int128/ghcp/releases/download/v1.13.1/ghcp_linux_amd64.zip
          unzip /tmp/ghcp.zip -d $HOME/bin
          chmod +x $HOME/bin/ghcp
      - run: |
          curl -L -o /tmp/ghr.tar.gz https://github.com/tcnksm/ghr/releases/download/v0.16.0/ghr_v0.16.0_linux_amd64.tar.gz
          tar -C /tmp -zxf /tmp/ghr.tar.gz
          mv /tmp/ghr_v0.16.0_linux_amd64/ghr $HOME/bin/ghr
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: "Start dockerized SSH server"
          command: |
            docker-compose -f ./.circleci/docker-compose.yml up -d
      - run: ./gradlew build
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: |
          if [ "$CIRCLE_BRANCH" = "master" ]; then
            ./.circleci/release-docs.sh
          fi
      - run: |
          if [ "$CIRCLE_TAG" ]; then
            ./.circleci/release-cli.sh
            ./gradlew bintrayUpload
          fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
            tags:
              only: /.*/
